########################################################################
# Pointwise - Proprietary software product of Pointwise, Inc.
#             Copyright (c) 1995-2012 Pointwise, Inc.
#             All rights reserved.
#
# module.mk for src\plugins\CaeUnsPrint3D plugin
########################################################################

########################################################################
########################################################################
#
#                   DO NOT EDIT THIS FILE
#
# To simplify SDK upgrades, the standard module.mk file should NOT be edited.
#
# If you want to modify a plugin's build process, you should rename
# modulelocal-sample.mk to modulelocal.mk and edit its settings.
#
# See the comments in modulelocal-sample.mk for more information.
#
#                   DO NOT EDIT THIS FILE
#
########################################################################
########################################################################

CaeUnsPrint3D_LOC := $(PLUGINS_LOC)/CaeUnsPrint3D
CaeUnsPrint3D_LIB := CaeUnsPrint3D$(DBG_SUFFIX)
CaeUnsPrint3D_CXX_LOC := $(CaeUnsPrint3D_LOC)
CaeUnsPrint3D_OBJ_LOC := $(PLUGINS_OBJ_LOC)/CaeUnsPrint3D

CaeUnsPrint3D_FULLNAME := lib$(CaeUnsPrint3D_LIB).$(SHLIB_SUFFIX)
CaeUnsPrint3D_FULLLIB := $(PLUGINS_DIST_DIR)/$(CaeUnsPrint3D_FULLNAME)

CaeUnsPrint3D_DEPS = \
	$(NULL)

MODCXXFILES := \
	runtimeWrite.cxx CaeUnsPrint3D.cxx \
	$(NULL)

# IMPORTANT:
# Must recompile the shared/XXX/.cxx files for each plugin. These .cxx files
# include the plugin specific settings defined in the ./CaeUnsPrint3D/*.h
# files.
CaeUnsPrint3D_SRC := \
	$(PLUGINS_RT_PWPSRC) \
	$(PLUGINS_RT_PWGMSRC) \
	$(PLUGINS_RT_CAEPSRC) \
	$(patsubst %,$(CaeUnsPrint3D_CXX_LOC)/%,$(MODCXXFILES))

CaeUnsPrint3D_SRC_CXX := $(filter %.cxx,$(MODCXXFILES))

# place the .o files generated from shared sources in the plugin's
# OBJ folder.
CaeUnsPrint3D_OBJ := \
	$(patsubst %.cxx,$(CaeUnsPrint3D_OBJ_LOC)/%.o,$(PLUGINS_RT_PWPFILES)) \
	$(patsubst %.cxx,$(CaeUnsPrint3D_OBJ_LOC)/%.o,$(PLUGINS_RT_PWGMFILES)) \
	$(patsubst %.cxx,$(CaeUnsPrint3D_OBJ_LOC)/%.o,$(PLUGINS_RT_CAEPFILES)) \
    $(patsubst %.cxx,$(CaeUnsPrint3D_OBJ_LOC)/%.o,$(CaeUnsPrint3D_SRC_CXX)) \
	$(NULL)

# To allow over-rides, search FIRST for headers in the local module's folder.
# For example, a site.h file in the local module's folder will preempt the
# file .../src/plugins/site.h
CaeUnsPrint3D_INCL = \
	-I$(CaeUnsPrint3D_LOC) \
	$(PLUGINS_RT_INCL) \
	$(NULL)

CaeUnsPrint3D_LIBS = \
	$(NULL)

CaeUnsPrint3D_MAINT_TARGETS := \
    CaeUnsPrint3D_info \
    CaeUnsPrint3D_install \
    CaeUnsPrint3D_installnow \
    CaeUnsPrint3D_uninstall


########################################################################
# Get (OPTIONAL) locally defined make targets. If a plugin developer wants
# to extend a plugin's make scheme, they should create a modulelocal.mk file
# in the plugin's base folder. To provide for future SDK upgrades, the standard
# module.mk file should NOT be directly edited.
#
ifneq ($(wildcard $(CaeUnsPrint3D_LOC)/modulelocal.mk),)
    CaeUnsPrint3D_DEPS += $(CaeUnsPrint3D_LOC)/modulelocal.mk
    include $(CaeUnsPrint3D_LOC)/modulelocal.mk
endif


# merge in plugin private settings

CaeUnsPrint3D_OBJ += \
    $(patsubst %.cxx,$(CaeUnsPrint3D_OBJ_LOC)/%.o,$(filter %.cxx,$(CaeUnsPrint3D_CXXFILES_PRIVATE))) \
	$(NULL)

CaeUnsPrint3D_SRC += \
	$(patsubst %,$(CaeUnsPrint3D_CXX_LOC)/%,$(CaeUnsPrint3D_CXXFILES_PRIVATE)) \
	$(NULL)

CaeUnsPrint3D_INCL += $(CaeUnsPrint3D_INCL_PRIVATE)
CaeUnsPrint3D_LIBS += $(CaeUnsPrint3D_LIBS_PRIVATE)
CaeUnsPrint3D_CXXFLAGS += $(CaeUnsPrint3D_CXXFLAGS_PRIVATE)
CaeUnsPrint3D_LDFLAGS += $(CaeUnsPrint3D_LDFLAGS_PRIVATE)
CaeUnsPrint3D_MAINT_TARGETS += $(CaeUnsPrint3D_MAINT_TARGETS_PRIVATE)
CaeUnsPrint3D_DEPS += $(CaeUnsPrint3D_DEPS_PRIVATE)

PLUGIN_MAINT_TARGETS += $(CaeUnsPrint3D_MAINT_TARGETS)
PLUGIN_OBJ += $(CaeUnsPrint3D_OBJ)

# add to plugin maint targets to the global .PHONY target
.PHONY: \
	$(CaeUnsPrint3D_MAINT_TARGETS) \
	$(NULL)


########################################################################
# Set the final build macros
CaeUnsPrint3D_CXXFLAGS += $(CXXFLAGS) $(PLUGINS_STDDEFS) $(CaeUnsPrint3D_INCL) \
    -DPWGM_HIDE_STRUCTURED_API


ifeq ($(machine),macosx)
CaeUnsPrint3D_LDFLAGS += -install_name "$(REL_BIN_TO_PW_LIB_DIR)/$(CaeUnsPrint3D_FULLNAME)"
else
CaeUnsPrint3D_LDFLAGS +=
endif


########################################################################
# list of plugin's build targets
#
CaeUnsPrint3D: $(CaeUnsPrint3D_FULLLIB)

$(CaeUnsPrint3D_FULLLIB): $(CaeUnsPrint3D_OBJ) $(CaeUnsPrint3D_DEPS)
	@echo "***"
	@echo "*** $@"
	@echo "***"
	@mkdir -p $(PLUGINS_DIST_DIR)
	$(SHLIB_LD) $(ARCH_FLAGS) $(CaeUnsPrint3D_LDFLAGS) -o $(CaeUnsPrint3D_FULLLIB) $(CaeUnsPrint3D_OBJ) $(CaeUnsPrint3D_LIBS) $(SYS_LIBS)

CaeUnsPrint3D_info:
	@echo ""
	@echo "--------------------------------------------------------------"
ifeq ($(machine),macosx)
	otool -L -arch all $(CaeUnsPrint3D_FULLLIB)
	@echo ""
endif
	file $(CaeUnsPrint3D_FULLLIB)
	@echo "--------------------------------------------------------------"
	@echo ""


########################################################################
# list of plugin's intermediate targets
#
$(CaeUnsPrint3D_OBJ_LOC):
	mkdir -p $(CaeUnsPrint3D_OBJ_LOC)

#.......................................................................
# build .d files for the plugin and each of the shared runtime sources
# the .d files will be placed in the plugins OBJ folder CaeUnsPrint3D_OBJ_LOC
$(CaeUnsPrint3D_OBJ_LOC)/%.d: $(CaeUnsPrint3D_CXX_LOC)/%.cxx
	@echo "Updating dependencies $(CaeUnsPrint3D_OBJ_LOC)/$*.d"
	@mkdir -p $(CaeUnsPrint3D_OBJ_LOC)
	@./depend.sh $(CaeUnsPrint3D_OBJ_LOC) $(CaeUnsPrint3D_CXXFLAGS) $< > $@

$(CaeUnsPrint3D_OBJ_LOC)/%.d: $(PLUGINS_RT_PWPLOC)/%.cxx
	@echo "Updating dependencies $(CaeUnsPrint3D_OBJ_LOC)/$*.d"
	@mkdir -p $(CaeUnsPrint3D_OBJ_LOC)
	@./depend.sh $(CaeUnsPrint3D_OBJ_LOC) $(CaeUnsPrint3D_CXXFLAGS) $< > $@

$(CaeUnsPrint3D_OBJ_LOC)/%.d: $(PLUGINS_RT_PWGMLOC)/%.cxx
	@echo "Updating dependencies $(CaeUnsPrint3D_OBJ_LOC)/$*.d"
	@mkdir -p $(CaeUnsPrint3D_OBJ_LOC)
	@./depend.sh $(CaeUnsPrint3D_OBJ_LOC) $(CaeUnsPrint3D_CXXFLAGS) $< > $@

$(CaeUnsPrint3D_OBJ_LOC)/%.d: $(PLUGINS_RT_CAEPLOC)/%.cxx
	@echo "Updating dependencies $(CaeUnsPrint3D_OBJ_LOC)/$*.d"
	@mkdir -p $(CaeUnsPrint3D_OBJ_LOC)
	@./depend.sh $(CaeUnsPrint3D_OBJ_LOC) $(CaeUnsPrint3D_CXXFLAGS) $< > $@

#.......................................................................
# build .o files for the plugin and each of the shared runtime sources.
# the .o files will be placed in the plugins OBJ folder CaeUnsPrint3D_OBJ_LOC
$(CaeUnsPrint3D_OBJ_LOC)/%.o: $(CaeUnsPrint3D_CXX_LOC)/%.cxx
	@echo "***"
	@echo "*** $*"
	@echo "***"
	@mkdir -p $(CaeUnsPrint3D_OBJ_LOC)
	$(CXX) $(CaeUnsPrint3D_CXXFLAGS) $(ARCH_FLAGS) -o $@ -c $<

$(CaeUnsPrint3D_OBJ_LOC)/%.o: $(PLUGINS_RT_PWPLOC)/%.cxx
	@echo "***"
	@echo "*** $*"
	@echo "***"
	@mkdir -p $(CaeUnsPrint3D_OBJ_LOC)
	$(CXX) $(CaeUnsPrint3D_CXXFLAGS) $(ARCH_FLAGS) -o $@ -c $<

$(CaeUnsPrint3D_OBJ_LOC)/%.o: $(PLUGINS_RT_PWGMLOC)/%.cxx
	@echo "***"
	@echo "*** $*"
	@echo "***"
	@mkdir -p $(CaeUnsPrint3D_OBJ_LOC)
	$(CXX) $(CaeUnsPrint3D_CXXFLAGS) $(ARCH_FLAGS) -o $@ -c $<

$(CaeUnsPrint3D_OBJ_LOC)/%.o: $(PLUGINS_RT_CAEPLOC)/%.cxx
	@echo "***"
	@echo "*** $*"
	@echo "***"
	@mkdir -p $(CaeUnsPrint3D_OBJ_LOC)
	$(CXX) $(CaeUnsPrint3D_CXXFLAGS) $(ARCH_FLAGS) -o $@ -c $<


########################################################################
# list of plugin's clean targets
#
CaeUnsPrint3D_cleandep:
	-$(RMR) $(CaeUnsPrint3D_OBJ_LOC)/*.d

CaeUnsPrint3D_clean:
	-$(RMR) $(CaeUnsPrint3D_OBJ_LOC)/*.{d,o}

CaeUnsPrint3D_distclean: CaeUnsPrint3D_clean
	-$(RMF) $(CaeUnsPrint3D_FULLLIB) > /dev/null 2>&1

########################################################################
# list of plugin's clean targets
#
CaeUnsPrint3D_install: install_validate CaeUnsPrint3D_installnow
	@echo "CaeUnsPrint3D Installed to '$(PLUGIN_INSTALL_FULLPATH)'"

CaeUnsPrint3D_installnow:
	-@$(CP) $(CaeUnsPrint3D_FULLLIB) "$(PLUGIN_INSTALL_FULLPATH)/libCaeUnsPrint3D.$(SHLIB_SUFFIX)"

CaeUnsPrint3D_uninstall:
	@echo "CaeUnsPrint3D Uninstalled from '$(PLUGIN_INSTALL_FULLPATH)'"
	-@$(RMF) "$(PLUGIN_INSTALL_FULLPATH)/libCaeUnsPrint3D.$(SHLIB_SUFFIX)"
